# Generated by Django 2.1.3 on 2019-01-28 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=5)),
                ('content', models.TextField(max_length=2000)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srcLanguage', models.CharField(max_length=3)),
                ('word', models.CharField(max_length=100)),
                ('destLanguage', models.CharField(max_length=3)),
                ('translatedWord1', models.CharField(max_length=100)),
                ('translatedWord2', models.CharField(max_length=100)),
                ('translatedWord3', models.CharField(max_length=100)),
                ('knownlevel', models.CharField(default=1, max_length=10)),
            ],
        ),
    ]
