# Generated by Django 2.1.3 on 2019-01-29 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_worddatabase_contentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddatabase',
            name='contentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
