# Generated by Django 2.1.3 on 2019-01-29 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translate', '0003_auto_20190129_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destLanguage', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='worddatabase',
            name='destLanguage',
            field=models.CharField(max_length=5),
        ),
    ]
