# Generated by Django 2.1.3 on 2019-02-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0004_auto_20190129_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddatabase',
            name='srcLanguage',
            field=models.CharField(max_length=5),
        ),
    ]
